sudo: required
language: python
python:
  - 3.6
notifications:
  email: false

script:
  - python test.py

before_install:
  - pip install colorama
  - pip install git+https://github.com/ayan-b/xena-GDC-ETL@xena

after_success:
  - git config user.email "travis@travis-ci.org"
  - git config user.name "traviscibot"
  - git status
  - git add TCGA-BRCA/Xena_Matrices
  - git commit -m "[skip ci] Add more data"
  - git push https://ayan-b:${GITHUB_TOKEN}@github.com/ayan-b/test-xena HEAD:master
